[package]
name = "pqckeys"
version = "0.1.1"
description = """
Pure Rust implementation of key formats for various post quantum cryptographic algorithms.
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/RustCrypto/formats/tree/master/x509"
categories = ["cryptography", "data-structures", "encoding", "no-std"]
keywords = ["crypto"]
readme = "README.md"
edition = "2021"
rust-version = "1.56"

[dependencies]
der = { version = "0.7.6", features = ["oid", "derive", "alloc"] }
x509-cert = { version = "0.2.3", default-features = false }
const-oid = { version = "0.9.2", features = ["db"] }
spki = { version = "0.7.2", features = ["alloc"] }
cms = { version = "0.2.1" }
flagset = { version = "0.4.3" }

[dev-dependencies]
hex-literal = "0.3"

[features]
alloc = ["der/alloc"]
std = ["der/std", "spki/std"]
pem = ["alloc", "der/pem"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
